# -*- coding: utf-8 -*-
"""LAB 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UlJPNVg_hStuyqV2RhKYmRmsNzbk_oNb
"""

2+3

10-5

121*22

12/2

a=5
print(a)

print("hello world")

print('hello world')

print("display the variable a",a)

x=5
y=10
z=x+y
print(z)
print("addition of two numbers",z)
print("addition",x,"&",y,"sum is",z)



x=7
y=14
z=x*y
print(z)
print("multiplication of two numbers",z)
print("multiplication",x,"&",y,"sum is",z)

x=87
y=2
z=x/y
print(z)
print("div of two numbers",z)
print("div",x,"&",y,"answer is",z)

x=33
y=21
z=x-y
print(z)
print("sub of two numbers",z)
print("sub",x,"&",y,"answer is",z)

a="2+4"
print(a)

a1="hello"
a2="world"
print(a1,a2)

a=input("Enter The Name ")
print(a)

a=int(input("enter the number"))
b=int(input("enter your age"))
print(a)
print(b)

x,y=input("enter the values").split()
input("enter the no: of boys",x)
input("enter the no: of girls",y)

print("helo")
print("world")
print("I am studying in BCA")

a="hello world"
print(a[0:4])
print(a[2:7])
print(a[2::2])